# .github/workflows/ci-pipeline.yml

name: Sentria Node.js CI Pipeline

# This workflow runs on pushes and pull requests to main branches.
on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  # This job will build the code, run checks, and scan for secrets.
  build-and-scan:
    name: Build, Lint & Scan
    runs-on: ubuntu-latest # Use a standard Linux environment for the job

    steps:
      # Step 1: Checks out repository's code onto the runner
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch all history so Gitleaks can scan the entire commit history
          fetch-depth: 0

      # Step 2: Sets up pnpm for dependency management
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # Specify pnpm version

      # Step 3: Sets up the Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Specify the Node.js version project uses
          cache: 'pnpm' # Enable caching for pnpm to speed up future runs

      # Step 4: Installs all project dependencies
      - name: Install dependencies
        run: pnpm install

      # Step 5: Generate Prisma Client
      # This is crucial for ensuring the client is up-to-date with the schema.
      - name: Generate Prisma Client
        run: pnpm prisma:generate

      # Step 6: Runs the linter and formatter in "check" mode
      # This uses existing 'lint' script from package.json but ensures it doesn't try to write files.
      # The pre-commit hook should have already formatted the code.
      - name: Run Linter & Formatter Check
        run: pnpm format && pnpm lint

      # Step 7: Scans for any hardcoded secrets or keys
      # This is the security check. It fails the job if secrets are found.
      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@v2
        env:
          # This allows the action to post comments on pull requests.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 8: Builds the TypeScript project
      # This verifies that code is free of type errors and can be compiled.
      - name: Build project
        run: pnpm run build

      # Step 9: Runs test suite
      # current "test" script is a placeholder. When you add real tests, they will run here.
      - name: Run tests
        run: pnpm run test
